// Code generated by "stringer -type=WebsiteCategory"; DO NOT EDIT.

package igdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WebsiteOfficial-1]
	_ = x[WebsiteWikia-2]
	_ = x[WebsiteWikipedia-3]
	_ = x[WebsiteFacebook-4]
	_ = x[WebsiteTwitter-5]
	_ = x[WebsiteTwitch-6]
	_ = x[WebsiteInstagram-8]
	_ = x[WebsiteYoutube-9]
	_ = x[WebsiteIphone-10]
	_ = x[WebsiteIpad-11]
	_ = x[WebsiteAndroid-12]
	_ = x[WebsiteSteam-13]
	_ = x[WebsiteReddit-14]
	_ = x[WebsiteDiscord-15]
	_ = x[WebsiteGooglePlus-16]
	_ = x[WebsiteTumblr-17]
	_ = x[WebsiteLinkedin-18]
	_ = x[WebsitePinterest-19]
	_ = x[WebsiteSoundcloud-20]
}

const (
	_WebsiteCategory_name_0 = "WebsiteOfficialWebsiteWikiaWebsiteWikipediaWebsiteFacebookWebsiteTwitterWebsiteTwitch"
	_WebsiteCategory_name_1 = "WebsiteInstagramWebsiteYoutubeWebsiteIphoneWebsiteIpadWebsiteAndroidWebsiteSteamWebsiteRedditWebsiteDiscordWebsiteGooglePlusWebsiteTumblrWebsiteLinkedinWebsitePinterestWebsiteSoundcloud"
)

var (
	_WebsiteCategory_index_0 = [...]uint8{0, 15, 27, 43, 58, 72, 85}
	_WebsiteCategory_index_1 = [...]uint8{0, 16, 30, 43, 54, 68, 80, 93, 107, 124, 137, 152, 168, 185}
)

func (i WebsiteCategory) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _WebsiteCategory_name_0[_WebsiteCategory_index_0[i]:_WebsiteCategory_index_0[i+1]]
	case 8 <= i && i <= 20:
		i -= 8
		return _WebsiteCategory_name_1[_WebsiteCategory_index_1[i]:_WebsiteCategory_index_1[i+1]]
	default:
		return "WebsiteCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
